{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lww",
    "module": "dingding",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rkg4cmpkwnfjheew6piar3ujre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dingding-1.0.0.jar",
          "url": "dingding-1.0.0.jar",
          "size": 16193,
          "sha512": "1d13c869558f3b6bc259e9fca33b1e12d619e62d2a6d26d857ba1d679ac8f22e362571b61fb32139c2e3496115a554c87d039e168307a86dad68e4db5f3fbb35",
          "sha256": "1283da841711802fae2d44a7e57a15c1aacfc43acd9e9769150ef805182a31e3",
          "sha1": "cb0c57ea79ea7fe58191aa73b7bcbe71c0f1317e",
          "md5": "eaa5e0ca1faddd88cdd81869951aa6df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "dingding-1.0.0.jar",
          "url": "dingding-1.0.0.jar",
          "size": 16193,
          "sha512": "1d13c869558f3b6bc259e9fca33b1e12d619e62d2a6d26d857ba1d679ac8f22e362571b61fb32139c2e3496115a554c87d039e168307a86dad68e4db5f3fbb35",
          "sha256": "1283da841711802fae2d44a7e57a15c1aacfc43acd9e9769150ef805182a31e3",
          "sha1": "cb0c57ea79ea7fe58191aa73b7bcbe71c0f1317e",
          "md5": "eaa5e0ca1faddd88cdd81869951aa6df"
        }
      ]
    }
  ]
}
